# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_registration', '0002_remove_basicinfo_d'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='game',
            field=models.CharField(choices=[('CS', 'Counter-Strike'), ('DOTA', 'DotA'), ('LOL', 'League of Legends')], max_length=4),
        ),
    ]
